[package]
org = "healthcare"
name = "coverage.api"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Coverage", "r4", "health.fhir.r4.international401"]
template = true
