# Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).

# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

openapi: 3.0.1
info:
  title: SMART Configuration API
  version: 1.0.0
  description: >
    This endpoint returns the SMART on FHIR well-known configuration JSON document that contains authorization
    endpoints and other relevant information required by SMART apps to initiate authorization.
    For more info, see the [SMART App Launch Framework](https://build.fhir.org/ig/HL7/smart-app-launch/conformance.html#using-well-known).
  contact:
    name: API Support
    url: https://wso2.com/contact/`
    email: user@email.com
tags:
  - name: SMART Configuration
  - name: FHIR
  - name: 4.0.1

paths:
  /.well-known/smart-configuration:
    get:
      summary: Get SMART on FHIR Configuration
      description: >
        Returns the SMART on FHIR `.well-known` configuration JSON document that describes the OAuth 2.0 endpoints
        and capabilities supported by the FHIR authorization server.
      operationId: getSmartConfiguration
      responses:
        '200':
          description: SMART configuration retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorization_endpoint:
                    type: string
                    format: uri
                  token_endpoint:
                    type: string
                    format: uri
                  introspection_endpoint:
                    type: string
                    format: uri
                  revocation_endpoint:
                    type: string
                    format: uri
                  capabilities:
                    type: array
                    items:
                      type: string
                example:
                  authorization_endpoint: https://auth.example.com/authorize
                  token_endpoint: https://auth.example.com/token
                  capabilities:
                    - launch-ehr
                    - client-confidential-asymmetric
        '500':
          description: Internal server error or FHIR-compliant error
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/FHIRError'

components:
  schemas:
    FHIRError:
      type: object
      properties:
        resourceType:
          type: string
          example: OperationOutcome
        issue:
          type: array
          items:
            type: object
            properties:
              severity:
                type: string
                example: fatal
              code:
                type: string
                example: exception
              diagnostics:
                type: string
                example: Unable to retrieve SMART configuration
