[package]
org = "wso2"
name = "bulk_export_client_service"
version = "0.1.0"
distribution = "2201.12.10"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.davincipdex220"
version = "1.0.1"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.davincihrex100"
version = "3.0.0"

