## server related configurables
[server_info]
version = "1.2.0"
name = "UnitedCare Health Insurance FHIR"
title = "FHIR Server"
status = "active"
experimental = true
date = "2025-01-01"
kind = "instance"
fhir_version = "4.0.1"
format = ["json"]
patch_format = ["application/json-patch+json"]
implementation_url = "<FHIR_BASE_URL>"
implementation_description = "UnitedCare Health Insurance FHIR"
interactions = ["search-system"]

## server security related configurables
[security]
cors = false
token_url = "<TOKEN_URL>"
revoke_url = "<REVOKE_URL>"
authorize_url = "<AUTHORIZE_URL>"
