[package]
org = "wso2"
name = "questionnaireresponse.api"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "QuestionnaireResponse", "r4", "health.fhir.r4"]
template = true
