export const fhirOperationConfigs = [
  {
    id: "patient-search",
    name: "Patient Search",
    endpoint: "/fhir/r4/Patient",
    showSearchButton: true,
    params: [
      {
        name: "_id",
        label: "Patient ID",
        type: "text",
        required: false,
        disabled: true,
      },
      { name: "given", label: "Given Name", type: "text", required: false },
      { name: "family", label: "Family Name", type: "text", required: false },
      {
        name: "address-city",
        label: "Address City",
        type: "text",
        required: false,
      },
      {
        name: "address-country",
        label: "Address Country",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "explanation-of-benefits",
    name: "Explanation of Benefits",
    endpoint: "/fhir/r4/ExplanationOfBenefit",
    showSearchButton: true,
    params: [
      {
        name: "patient",
        label: "Patient ID",
        type: "text",
        required: false,
        disabled: true,
      },
      {
        name: "_id",
        label: "Explanation of Benefits ID",
        type: "text",
        required: false,
      },
      { name: "_profile", label: "Profile", type: "text", required: false },
      {
        name: "_lastUpdated",
        label: "Last Updated",
        type: "date",
        required: false,
      },
      {
        name: "identifier",
        label: "Identifier",
        type: "text",
        required: false,
      },
      { name: "created", label: "Created", type: "date", required: false },
    ],
  },
  {
    id: "coverage",
    name: "Coverage",
    endpoint: "/fhir/r4/Coverage",
    showSearchButton: true,
    params: [
      {
        name: "patient",
        label: "Patient ID",
        type: "text",
        required: false,
        disabled: true,
      },
      { name: "_id", label: "Coverage ID", type: "text", required: false },
    ],
  },
  {
    id: "claim-response",
    name: "Prior Authorization Data",
    endpoint: "/claimresponse/fhir/r4/ClaimResponse",
    displayEndpoint: "/fhir/r4/ClaimResponse",
    showSearchButton: true,
    params: [
      {
        name: "patient",
        label: "Patient ID (Coming Soon)",
        type: "text",
        required: false,
        disabled: false,
      },
      { name: "_id", label: "Coverage ID", type: "text", required: false, defaultValue: "12344", },
      { name: "created ", label: "Created (Coming Soon)", type: "date", required: false },
      { name: "use", label: "Use (Coming Soon)", type: "text", required: false},
    ],
  },
];
