[package]
org = "wso2"
name = "claim.api"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Claim", "r4", "health.fhir.r4.davincipas"]
template = true
