openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9099"
paths:
  /export:
    get:
      operationId: getExport
      parameters:
      - name: _outputFormat
        in: query
        schema:
          type: string
          nullable: true
      - name: _since
        in: query
        schema:
          type: string
          nullable: true
      - name: _type
        in: query
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
    post:
      operationId: postExport
      parameters:
      - name: _outputFormat
        in: query
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      - name: _since
        in: query
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      - name: _type
        in: query
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchedPatient'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /export/group/{group_id}:
    get:
      operationId: getExportGroupGroupId
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      - name: _outputFormat
        in: query
        schema:
          type: string
          nullable: true
      - name: _since
        in: query
        schema:
          type: string
          nullable: true
      - name: _type
        in: query
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /status:
    get:
      operationId: getStatus
      parameters:
      - name: exportId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /download:
    get:
      operationId: getDownload
      parameters:
      - name: location
        in: query
        required: true
        schema:
          type: string
      responses: {}
  /file/download:
    get:
      operationId: getFileDownload
      parameters:
      - name: exportId
        in: query
        required: true
        schema:
          type: string
      - name: resourceType
        in: query
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    MatchedPatient:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        canonical:
          type: string
        identifiers:
          type: object
          additionalProperties:
            type: string
