import {
  ACTIVE_STEP,
  CDS_HOOK,
  CDS_REQUEST,
  CDS_REQUEST_METHOD,
  CDS_REQUEST_URL,
  CDS_RESPONSE,
  CLAIM_REQUEST,
  CLAIM_REQUEST_METHOD,
  CLAIM_REQUEST_URL,
  CLAIM_RESPONSE,
  IS_PROCESS,
  MEDICATION_REQUEST,
  MEDICATION_REQUEST_METHOD,
  MEDICATION_REQUEST_URL,
  MEDICATION_RESPONSE,
  QUESTIONNAIRE_PACKAGE_REQUEST,
  QUESTIONNAIRE_PACKAGE_REQUEST_METHOD,
  QUESTIONNAIRE_PACKAGE_RESPONSE,
  QUESTIONNAIRE_PACKAGE_URL,
  QUESTIONNAIRE_RESPONSE,
  QUESTIONNAIRE_RESPONSE_REQUEST,
  QUESTIONNAIRE_RESPONSE_METHOD,
  QUESTIONNAIRE_RESPONSE_URL,
  SELECTED_PATIENT_ID,
  SELECTED_PATIENT_NAME,
  STEPS,
  TIMESTAMP,
  LOGGEDIN_USER,
} from "../constants/localStorageVariables";

export const clearLocalStorageFully = () => {
  localStorage.removeItem(ACTIVE_STEP);
  localStorage.removeItem(CDS_HOOK);
  localStorage.removeItem(CDS_REQUEST);
  localStorage.removeItem(CDS_REQUEST_METHOD);
  localStorage.removeItem(CDS_REQUEST_URL);
  localStorage.removeItem(CDS_RESPONSE);
  localStorage.removeItem(CLAIM_REQUEST);
  localStorage.removeItem(CLAIM_REQUEST_METHOD);
  localStorage.removeItem(CLAIM_REQUEST_URL);
  localStorage.removeItem(CLAIM_RESPONSE);
  localStorage.removeItem(IS_PROCESS);
  localStorage.removeItem(LOGGEDIN_USER);
  localStorage.removeItem(MEDICATION_REQUEST);
  localStorage.removeItem(MEDICATION_REQUEST_METHOD);
  localStorage.removeItem(MEDICATION_REQUEST_URL);
  localStorage.removeItem(MEDICATION_RESPONSE);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_REQUEST);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_REQUEST_METHOD);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_RESPONSE);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_URL);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE_REQUEST);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE_METHOD);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE_URL);
  localStorage.removeItem(SELECTED_PATIENT_ID);
  localStorage.removeItem(SELECTED_PATIENT_NAME);
  localStorage.removeItem(STEPS);
  localStorage.removeItem(TIMESTAMP);
};

export const clearLocalStorageForPAPrococess = () => {
  localStorage.removeItem(ACTIVE_STEP);
  localStorage.removeItem(CDS_HOOK);
  localStorage.removeItem(CDS_REQUEST);
  localStorage.removeItem(CDS_REQUEST_METHOD);
  localStorage.removeItem(CDS_REQUEST_URL);
  localStorage.removeItem(CDS_RESPONSE);
  localStorage.removeItem(CLAIM_REQUEST);
  localStorage.removeItem(CLAIM_REQUEST_METHOD);
  localStorage.removeItem(CLAIM_REQUEST_URL);
  localStorage.removeItem(CLAIM_RESPONSE);
  localStorage.removeItem(MEDICATION_REQUEST);
  localStorage.removeItem(MEDICATION_REQUEST_METHOD);
  localStorage.removeItem(MEDICATION_REQUEST_URL);
  localStorage.removeItem(MEDICATION_RESPONSE);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_REQUEST);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_REQUEST_METHOD);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_RESPONSE);
  localStorage.removeItem(QUESTIONNAIRE_PACKAGE_URL);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE_REQUEST);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE_METHOD);
  localStorage.removeItem(QUESTIONNAIRE_RESPONSE_URL);
  localStorage.removeItem(STEPS);
  localStorage.removeItem(TIMESTAMP);
};
