[package]
org = "wso2"
name = "prior.authorization"
version = "1.0.0"
distribution = "2201.12.3"
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501", "Prior Authorization"]

[build-options]
observabilityIncluded = true
