[package]
org = "wso2"
name = "practitioner.api"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Practitioner", "r4", "health.fhir.r4.uscore501"]
template = true
