# Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).

# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

openapi: 3.0.1
info:
  title: FHIR R4 Metadata API
  version: 1.0.0
  description: |
    This API provides the FHIR R4 Capability Statement, which is a key part of the overall conformance framework in FHIR.
    It describes the features of the software or rules for an application and can be used for compatibility testing,
    code generation, or conformance assessment.
  contact:
    name: API Support
    url: https://wso2.com/contact/`
    email: user@email.com
tags:
  - name: CapabilityStatement
  - name: 4.0.1

paths:
  /:
    get:
      summary: Get FHIR R4 Capability Statement
      description: |
        Returns the capability statement in JSON format.
        For more info, see [HL7 CapabilityStatement](https://hl7.org/fhir/capabilitystatement.html).
      operationId: getCapabilityStatement
      responses:
        '200':
          description: Capability statement returned successfully
          content:
            application/fhir+json:
              schema:
                type: object
              example:
                resourceType: CapabilityStatement
                status: active
                kind: instance
        '500':
          description: Internal server error or FHIR error response
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                        code:
                          type: string
                        diagnostics:
                          type: string 
components:
  schemas:
    FHIRError:
      type: object
      properties:
        resourceType:
          type: string
          example: OperationOutcome
        issue:
          type: array
          items:
            type: object
            properties:
              severity:
                type: string
              code:
                type: string
              diagnostics:
                type: string
