// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).

// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// AUTO-GENERATED FILE.
// This file is auto-generated by Ballerina.

import ballerina/http;
import ballerinax/health.clients.fhir;
import ballerinax/health.fhir.r4;
import ballerinax/health.fhir.r4.international401;
import ballerinax/health.fhir.r4.parser;

isolated international401:Questionnaire[] questionnaires = [];
isolated int createOperationNextIdQuestionnaire = 5;

isolated international401:Parameters[] parameters = [];
isolated int createOperationNextIdQuestionnairePackage = 33;

public isolated function questionnairePackage(international401:Parameters payload) returns r4:FHIRError|international401:Parameters {
    international401:Parameters|error parameters = parser:parseWithValidation(payload.toJson(), international401:Parameters).ensureType();

    if parameters is error {
        return r4:createFHIRError(parameters.message(), r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
    } else {
        return getByIdQuestionnairePackage("32");
    }
}

public isolated function getByIdQuestionnairePackage(string id) returns r4:FHIRError|international401:Parameters {
    lock {
        foreach var item in parameters {
            string result = item.id ?: "";

            if result == id {
                return item.clone();
            }
        }
    }
    return r4:createFHIRError(string `Cannot find a Questionnaire resource with id: ${id}`, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_NOT_FOUND);
}

public isolated function createQuestionnaire(Questionnaire payload) returns r4:FHIRError|international401:Questionnaire {
    international401:Questionnaire|error patient = parser:parseWithValidation(payload.toJson(), international401:Questionnaire).ensureType();

    if patient is error {
        return r4:createFHIRError(patient.message(), r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
    } else {
        lock {
            patient.id = (++createOperationNextIdQuestionnaire).toBalString();
        }

        lock {
            questionnaires.push(patient.clone());
        }

        return patient;
    }
}

public isolated function getByIdQuestionnaire(string id) returns r4:FHIRError|international401:Questionnaire {
    lock {
        foreach var item in questionnaires {
            string result = item.id ?: "";

            if result == id {
                return item.clone();
            }
        }
    }
    return r4:createFHIRError(string `Cannot find a Questionnaire resource with id: ${id}`, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_NOT_FOUND);
}

public isolated function updateQuestionnaire(json payload) returns r4:FHIRError|fhir:FHIRResponse {
    return r4:createFHIRError("Not implemented", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_NOT_IMPLEMENTED);

}

public isolated function patchResourceQuestionnaire(string 'resource, string id, json payload) returns r4:FHIRError|fhir:FHIRResponse {
    return r4:createFHIRError("Not implemented", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_NOT_IMPLEMENTED);
}

public isolated function deleteQuestionnaire(string 'resource, string id) returns r4:FHIRError|fhir:FHIRResponse {
    return r4:createFHIRError("Not implemented", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_NOT_IMPLEMENTED);

}

public isolated function searchQuestionnaire(string 'resource, map<string[]>? searchParameters = ()) returns r4:FHIRError|r4:Bundle {
    r4:Bundle bundle = {
        'type: "collection"
    };

    if searchParameters is map<string[]> {
        if searchParameters.keys().length() == 1 {
            lock {
                r4:BundleEntry[] bundleEntries = [];
                foreach var item in questionnaires {
                    r4:BundleEntry bundleEntry = {
                        'resource: item
                    };
                    bundleEntries.push(bundleEntry);
                }
                r4:Bundle BundleClone = bundle.clone();
                BundleClone.entry = bundleEntries;
                return BundleClone.clone();
            }
        }

        foreach var 'key in searchParameters.keys() {
            match 'key {
                "_id" => {
                    international401:Questionnaire byId = check getByIdQuestionnaire(searchParameters.get('key)[0]);
                    bundle.entry = [
                        {
                            'resource: byId
                        }
                    ];
                    return bundle;
                }
                _ => {
                    return r4:createFHIRError(string `Not supported search parameter: ${'key}`, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_NOT_IMPLEMENTED);
                }
            }
        }
    }

    return bundle;
}

function loadQuestionnairePackageData() returns error? {
    lock {
        json questionnaireJson = {
            "resourceType": "Parameters",
            "id": "32",
            "parameter": [
                {
                    "name": "PackageBundle",
                    "resource": {
                        "resourceType": "Bundle",
                        "type": "collection",
                        "entry": [
                            {
                                "resource": {
                                    "resourceType": "Questionnaire",
                                    "id": "4",
                                    "status": "active",
                                    "title": "Prior Authorization for Aimovig 70 mg Injection",
                                    "subjectType": ["Patient"],
                                    "extension": [
                                        {
                                            "url": "http://hl7.org/fhir/StructureDefinition/cqf-library",
                                            "extension": [
                                                {
                                                    "url": "library",
                                                    "valueBase64Binary": "bGlicmFyeSBBaW1vdmlnUHJpb3JBdXRoIHZlcnNpb24gJzEuMC4wJwoKdXNpbmcgRkhJUiB2ZXJzaW9uICc0LjAuMScKCmluY2x1ZGUgRkhJUkhlbHBlcnMgdmVyc2lvbiAnNC4wLjEn..."
                                                }
                                            ]
                                        }
                                    ],
                                    "item": [
                                        {
                                            "linkId": "1",
                                            "text": "Has the patient been diagnosed with chronic migraines?",
                                            "type": "boolean"
                                        },
                                        {
                                            "linkId": "2",
                                            "text": "Has the patient tried other preventive migraine treatments?",
                                            "type": "boolean"
                                        },
                                        {
                                            "linkId": "3",
                                            "text": "Please list previous medications used for migraine prevention.",
                                            "type": "string"
                                        },
                                        {
                                            "linkId": "4",
                                            "text": "What is the frequency of migraines per month?",
                                            "type": "integer"
                                        },
                                        {
                                            "linkId": "5",
                                            "text": "Has the patient experienced side effects or lack of effectiveness with prior treatments?",
                                            "type": "boolean"
                                        },
                                        {
                                            "linkId": "6",
                                            "text": "Does the patient have any contraindications to other migraine medications?",
                                            "type": "boolean"
                                        },
                                        {
                                            "linkId": "7",
                                            "text": "Does the patient have insurance coverage for Aimovig?",
                                            "type": "boolean"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        };

        international401:Parameters p = check parser:parse(questionnaireJson, international401:Parameters).ensureType();
        parameters.push(p);
    }
}

function loadQuestionnaireData() returns error? {
    lock {
        json questionnaireJson = {
            "resourceType": "Questionnaire",
            "id": "4",
            "status": "active",
            "title": "Prior Authorization for Aimovig 70 mg Injection",
            "subjectType": ["Patient"],
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/cqf-library",
                    "extension": [
                        {
                            "url": "library",
                            "valueBase64Binary": "bGlicmFyeSBBaW1vdmlnUHJpb3JBdXRoIHZlcnNpb24gJzEuMC4wJwoKdXNpbmcgRkhJUiB2ZXJzaW9uICc0LjAuMScKCmluY2x1ZGUgRkhJUkhlbHBlcnMgdmVyc2lvbiAnNC4wLjEnCgpjb250ZXh0IFBhdGllbnQKCi8vIERlZmluZSBDaHJvbmljIE1pZ3JhaW5lIERpYWdub3NpcwpkZWZpbmUgIkNocm9uaWMgTWlncmFpbmUgRGlhZ25vc2lzIjoKICBleGlzdHMgKAogICAgW0NvbmRpdGlvbjogIjM3Nzk2MDA5Il0gLy8gU05PTUVEIGNvZGUgZm9yIE1pZ3JhaW5lCiAgICB3aGVyZSBzdGF0dXMgPSAnYWN0aXZlJwogICkKCi8vIERlZmluZSBQcmV2aW91cyBQcmV2ZW50aXZlIE1pZ3JhaW5lIFRyZWF0bWVudHMKZGVmaW5lICJQcmV2aW91cyBQcmV2ZW50aXZlIFRyZWF0bWVudHMiOgogIGV4aXN0cyAoCiAgICBbTWVkaWNhdGlvblJlcXVlc3RdCiAgICB3aGVyZSBtZWRpY2F0aW9uIGluICgKICAgICAgJ1Byb3ByYW5vbG9sJywgJ1RvcGlyYW1hdGUnLCAnQW1pdHJpcHR5bGluZScsICdCb3RveCcsICdDR1JQIEluaGliaXRvcnMnCiAgICApCiAgICBhbmQgc3RhdHVzIGluICgnY29tcGxldGVkJywgJ2FjdGl2ZScpCiAgKQoKLy8gRGVmaW5lIE1pZ3JhaW5lIEZyZXF1ZW5jeSBDcml0ZXJpYQpkZWZpbmUgIk1pZ3JhaW5lIEZyZXF1ZW5jeSBIaWdoIjoKICBleGlzdHMgKAogICAgW09ic2VydmF0aW9uXQogICAgd2hlcmUgY29kZSA9ICdtaWdyYWluZS1mcmVxdWVuY3knIGFuZCB2YWx1ZVF1YW50aXR5LnZhbHVlID49IDQKICApCgovLyBEZWZpbmUgQ29udHJhaW5kaWNhdGlvbnMgdG8gT3RoZXIgTWlncmFpbmUgTWVkaWNhdGlvbnMKZGVmaW5lICJIYXMgQ29udHJhaW5kaWNhdGlvbnMiOgogIGV4aXN0cyAoCiAgICBbQ29uZGl0aW9uXQogICAgd2hlcmUgY29kZSBpbiAoCiAgICAgICdBbGxlcmd5IHRvIGJldGEgYmxvY2tlcnMnLCAnUmVuYWwgZGlzZWFzZScsICdMaXZlciBkaXNlYXNlJwogICAgKQogICkKCi8vIERlZmluZSBJbnN1cmFuY2UgQ292ZXJhZ2UgQ2hlY2sKZGVmaW5lICJJbnN1cmFuY2UgQ292ZXJhZ2UiOgogIGV4aXN0cyAoCiAgICBbQ292ZXJhZ2VdCiAgICB3aGVyZSBwYXlvci5yZWZlcmVuY2UgPSAnT3JnYW5pemF0aW9uL2luc3VyYW5jZS1vcmcnCiAgKQoKLy8gRGVmaW5lIENyaXRlcmlhIGZvciBBcHByb3ZhbApkZWZpbmUgIlByaW9yIEF1dGhvcml6YXRpb24gQXBwcm92ZWQiOgogICJDaHJvbmljIE1pZ3JhaW5lIERpYWdub3NpcyIgYW5kCiAgIlByZXZpb3VzIFByZXZlbnRpdmUgVHJlYXRtZW50cyIgYW5kCiAgIk1pZ3JhaW5lIEZyZXF1ZW5jeSBIaWdoIiBhbmQKICAoIkhhcyBDb250cmFpbmRpY2F0aW9ucyIgb3IgIkluc3VyYW5jZSBDb3ZlcmFnZSIp"
                        }
                    ]
                }
            ],
            "item": [
                {
                    "linkId": "1",
                    "text": "Has the patient been diagnosed with chronic migraines?",
                    "type": "boolean"
                },
                {
                    "linkId": "2",
                    "text": "Has the patient tried other preventive migraine treatments?",
                    "type": "boolean"
                },
                {
                    "linkId": "3",
                    "text": "Please list previous medications used for migraine prevention.",
                    "type": "string"
                },
                {
                    "linkId": "4",
                    "text": "What is the frequency of migraines per month?",
                    "type": "integer"
                },
                {
                    "linkId": "5",
                    "text": "Has the patient experienced side effects or lack of effectiveness with prior treatments?",
                    "type": "boolean"
                },
                {
                    "linkId": "6",
                    "text": "Does the patient have any contraindications to other migraine medications?",
                    "type": "boolean"
                },
                {
                    "linkId": "7",
                    "text": "Does the patient have insurance coverage for Aimovig?",
                    "type": "boolean"
                }
            ]
        };

        international401:Questionnaire questionnaire = check parser:parse(questionnaireJson, international401:Questionnaire).ensureType();
        questionnaires.push(questionnaire);
    }

}
